*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMFR_TUTOP.                      " Global Data
  INCLUDE LZWMFR_TUUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMFR_TUF00                            . " subprograms
  INCLUDE LZWMFR_TUI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMFR_TUF...                      " Subprograms
* INCLUDE LZWMFR_TUO...                      " PBO-Modules
* INCLUDE LZWMFR_TUI...                      " PAI-Modules
