*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTIPOPALETETOP.                   " Global Data
  INCLUDE LZTIPOPALETEUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTIPOPALETEF00                         . " subprograms
  INCLUDE LZTIPOPALETEI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTIPOPALETEF...                   " Subprograms
* INCLUDE LZTIPOPALETEO...                   " PBO-Modules
* INCLUDE LZTIPOPALETEI...                   " PAI-Modules
