FUNCTION ZWM_LM_DATA_SELECTION_OUTPUT.
*"--------------------------------------------------------------------
*"*"Interface local:
*"       IMPORTING
*"             VALUE(IF_FLAG_INBOUND) TYPE  CHAR1 DEFAULT SPACE
*"       TABLES
*"              IT_V2_OUTP_SEL STRUCTURE  RANGE_C4
*"              IT_V4_OUTP_SEL STRUCTURE  RANGE_C4
*"              IT_V5_OUTP_SEL STRUCTURE  RANGE_C4
*"              IT_E1_OUTP_SEL STRUCTURE  RANGE_C4 OPTIONAL
*"              ET_OUTPUT_V2 STRUCTURE  LIPOV_OUTPUT
*"              ET_OUTPUT_V4 STRUCTURE  LIPOV_OUTPUT
*"              ET_OUTPUT_V5 STRUCTURE  LIPOV_OUTPUT
*"              ET_OUTPUT_E1 STRUCTURE  LIPOV_OUTPUT OPTIONAL
*"--------------------------------------------------------------------

  DATA: LT_OUTPUT_V2 LIKE LIPOV_OUTPUT OCCURS 0,
        LT_OUTPUT_V4 LIKE LIPOV_OUTPUT OCCURS 0,
        LT_OUTPUT_V5 LIKE LIPOV_OUTPUT OCCURS 0,
        LT_OUTPUT_E1 LIKE LIPOV_OUTPUT OCCURS 0.

  IF IF_FLAG_INBOUND EQ SPACE.

    PERFORM OUTPUT_SELECTION TABLES IT_V2_OUTP_SEL
                                    ET_OUTPUT_V2
                              USING 'V2'.

    PERFORM OUTPUT_SELECTION TABLES IT_V4_OUTP_SEL
                                    ET_OUTPUT_V4
                              USING 'V4'.

    PERFORM OUTPUT_SELECTION TABLES IT_V5_OUTP_SEL
                                    ET_OUTPUT_V5
                              USING 'V5'.

  ELSE.
    PERFORM OUTPUT_SELECTION TABLES IT_E1_OUTP_SEL
                                    ET_OUTPUT_E1
                              USING 'E1'.
  ENDIF.

  CALL CUSTOMER-FUNCTION '002'
      TABLES
         CT_OUTPUT_V2  = LT_OUTPUT_V2
         CT_OUTPUT_V4  = LT_OUTPUT_V4
         CT_OUTPUT_V5  = LT_OUTPUT_V5
         CT_OUTPUT_E1  = LT_OUTPUT_E1.

  IF IF_FLAG_INBOUND EQ SPACE.
    APPEND LINES OF LT_OUTPUT_V2 TO ET_OUTPUT_V2.
    APPEND LINES OF LT_OUTPUT_V4 TO ET_OUTPUT_V4.
    APPEND LINES OF LT_OUTPUT_V5 TO ET_OUTPUT_V5.
    SORT ET_OUTPUT_V2 BY KSCHL KAPPL SELKZ DESCENDING.
    SORT ET_OUTPUT_V4 BY KSCHL KAPPL SELKZ DESCENDING.
    SORT ET_OUTPUT_V5 BY KSCHL KAPPL SELKZ DESCENDING.
    DELETE ADJACENT DUPLICATES FROM ET_OUTPUT_V2
                               COMPARING KSCHL KAPPL.
    DELETE ADJACENT DUPLICATES FROM ET_OUTPUT_V4
                               COMPARING KSCHL KAPPL.
    DELETE ADJACENT DUPLICATES FROM ET_OUTPUT_V5
                               COMPARING KSCHL KAPPL.
  ELSE.
    APPEND LINES OF LT_OUTPUT_E1 TO ET_OUTPUT_E1.
    SORT ET_OUTPUT_E1 BY KSCHL KAPPL SELKZ DESCENDING.
    DELETE ADJACENT DUPLICATES FROM ET_OUTPUT_E1
                               COMPARING KSCHL KAPPL.
  ENDIF.
ENDFUNCTION.
