*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWM_DOCU_YEARTOP.                 " Global Data
  INCLUDE LZWM_DOCU_YEARUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWM_DOCU_YEARF00                       . " subprograms
  INCLUDE LZWM_DOCU_YEARI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWM_DOCU_YEARF...                 " Subprograms
* INCLUDE LZWM_DOCU_YEARO...                 " PBO-Modules
* INCLUDE LZWM_DOCU_YEARI...                 " PAI-Modules
