"Name: \PR:SAPLLSAM\FO:TA_LF_ERSTELLEN\SE:END\EI
ENHANCEMENT 0 ZWM_MESSAGE_L3008.
FIELD-SYMBOLS: <fs_matnr> TYPE matnr.

ASSIGN ('(SAPLL03B)LTAP-MATNR') TO <fs_matnr>.

** Modificar Mensagem de Erro
IF SY-MSGTY = 'E' AND SY-MSGID = 'L3' AND SY-MSGNO = '008'.

  MOVE '278'       TO LMESS-MSGNO.
  MOVE 'ZWMMSG001' TO LMESS-MSGID.

  CALL FUNCTION 'CONVERSION_EXIT_MATN1_OUTPUT'
    EXPORTING
      input        = <fs_matnr>
   IMPORTING
     OUTPUT        = LMESS-MSGV1.

*  MOVE <fs_matnr>  TO LMESS-MSGV1.
*  MOVE SY-MSGV2 TO LMESS-MSGV2.
*  MOVE SY-MSGV3 TO LMESS-MSGV3.
*  MOVE SY-MSGV4 TO LMESS-MSGV4.

  CALL FUNCTION 'L_MESSAGE_AUFBEREITEN' EXPORTING I_MESS = LMESS
                                        IMPORTING O_TEXT = HLP_TEXT.

  MOVE HLP_TEXT TO LSAM-FTEXT.
ENDIF.

ENDENHANCEMENT.
