*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMFUNC1TOP.                      " Global Data
  INCLUDE LZWMFUNC1UXX.                      " Function Modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMFUNC1F...                      " Subprograms
* INCLUDE LZWMFUNC1O...                      " PBO-Modules
* INCLUDE LZWMFUNC1I...                      " PAI-Modules

INCLUDE LZWMFUNC1F01.

INCLUDE LZWMFUNC1O01.

INCLUDE LZWMFUNC1I01.

INCLUDE LZWMFUNC1I02.

INCLUDE LZWMFUNC1O02.

INCLUDE LZWMFUNC1O03.

INCLUDE LZWMFUNC1I03.

INCLUDE LZWMFUNC1I04.

INCLUDE LZWMFUNC1I05.

INCLUDE LZWMFUNC1I06.

INCLUDE LZWMFUNC1F02.

INCLUDE LZWMFUNC1I07.

INCLUDE LZWMFUNC1F03.

INCLUDE LZWMFUNC1F04.

INCLUDE LZWMFUNC1I08.

INCLUDE LZWMFUNC1O04.

INCLUDE LZWMFUNC1O05.

INCLUDE LZWMFUNC1I09.

INCLUDE LZWMFUNC1F05.

INCLUDE LZWMFUNC1O06.

INCLUDE LZWMFUNC1I10.

INCLUDE LZWMFUNC1O07.

INCLUDE LZWMFUNC1I11.

INCLUDE LZWMFUNC1I12.

INCLUDE LZWMFUNC1I13.

INCLUDE LZWMFUNC1O08.

INCLUDE LZWMFUNC1I14.

INCLUDE LZWMFUNC1O09.

INCLUDE LZWMFUNC1I15.

INCLUDE LZWMFUNC1O10.

INCLUDE LZWMFUNC1I16.

INCLUDE LZWMFUNC1F07.

INCLUDE LZWMFUNC1F06.

INCLUDE LZWMFUNC1I17.

INCLUDE LZWMFUNC1O11.

INCLUDE LZWMFUNC1I18.

INCLUDE LZWMFUNC1I19.
