*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMLOGTOP.                        " Global Data
  INCLUDE LZWMLOGUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMLOGF00                              . " subprograms
  INCLUDE LZWMLOGI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMLOGF...                        " Subprograms
* INCLUDE LZWMLOGO...                        " PBO-Modules
* INCLUDE LZWMLOGI...                        " PAI-Modules
