*&---------------------------------------------------------------------*
*&  Include           ZWMREPT080                                       *
*&---------------------------------------------------------------------*
tables:
        vekp,
        vepo,
        vbpa,
        lein,
        ltap,
        ltak,
        likp,
        adrc,
        zwm026h,
        zwm026.


data: begin of tabi occurs 0,
        tipo(1) type c,
        matnr like vepo-matnr,
        charg like vepo-charg,
        exidv like vekp-exidv,
        erdat_sscc like vekp-erdat,
        eruhr_sscc like vekp-eruhr,
        exidv_pik like vekp-exidv,
        bdatu like ltak-bdatu,
        bzeit like ltak-bzeit,
        lgtyp like lein-lgtyp,
        lgpla like lein-lgpla,
        bdatu_sai like ltak-bdatu,
        bzeit_sai like ltak-bzeit,
        vbeln like likp-vbeln,
        kunnr like likp-kunnr,
        nome like kna1-name1,
        bdatu_rep like ltak-bdatu,
        bzeit_rep like ltak-bzeit,
        erdat_pik like vekp-erdat,
        eruhr_pik like vekp-eruhr,
        texto(5) type c,
        benum like ltak-benum,
        vemng like vepo-vemng,
      end of tabi.
* tabela interna para dados extra de picking
data: begin of p_tabi occurs 0,
        tipo(1) type c,
        matnr like vepo-matnr,
        charg like vepo-charg,
        exidv like vekp-exidv,
        erdat_sscc like vekp-erdat,
        eruhr_sscc like vekp-eruhr,
        exidv_pik like vekp-exidv,
        bdatu like ltak-bdatu,
        bzeit like ltak-bzeit,
        lgtyp like lein-lgtyp,
        lgpla like lein-lgpla,
        bdatu_sai like ltak-bdatu,
        bzeit_sai like ltak-bzeit,
        vbeln like likp-vbeln,
        kunnr like likp-kunnr,
        nome like kna1-name1,
        bdatu_rep like ltak-bdatu,
        bzeit_rep like ltak-bzeit,
        erdat_pik like vekp-erdat,
        eruhr_pik like vekp-eruhr,
        texto(5) type c,
        benum like ltak-benum,
        vemng like vepo-vemng,
      end of p_tabi.
*
* tabela interna para dados iniciais de picking
data: begin of pi_tabi occurs 0,
        tipo(1) type c,
        matnr like vepo-matnr,
        charg like vepo-charg,
        exidv like vekp-exidv,
        erdat_sscc like vekp-erdat,
        eruhr_sscc like vekp-eruhr,
        exidv_pik like vekp-exidv,
        bdatu like ltak-bdatu,
        bzeit like ltak-bzeit,
        lgtyp like lein-lgtyp,
        lgpla like lein-lgpla,
        bdatu_sai like ltak-bdatu,
        bzeit_sai like ltak-bzeit,
        vbeln like likp-vbeln,
        kunnr like likp-kunnr,
        nome like kna1-name1,
        bdatu_rep like ltak-bdatu,
        bzeit_rep like ltak-bzeit,
        erdat_pik like vekp-erdat,
        eruhr_pik like vekp-eruhr,
        texto(5) type c,
        benum like ltak-benum,
        vemng like vepo-vemng,
      end of pi_tabi.
*
data: begin of px_tabi occurs 0,
        tipo(1) type c,
        matnr like vepo-matnr,
        charg like vepo-charg,
        exidv like vekp-exidv,
        erdat_sscc like vekp-erdat,
        eruhr_sscc like vekp-eruhr,
        exidv_pik like vekp-exidv,
        bdatu like ltak-bdatu,
        bzeit like ltak-bzeit,
        lgtyp like lein-lgtyp,
        lgpla like lein-lgpla,
        bdatu_sai like ltak-bdatu,
        bzeit_sai like ltak-bzeit,
        vbeln like likp-vbeln,
        kunnr like likp-kunnr,
        nome like kna1-name1,
        bdatu_rep like ltak-bdatu,
        bzeit_rep like ltak-bzeit,
        erdat_pik like vekp-erdat,
        eruhr_pik like vekp-eruhr,
        texto(5) type c,
        benum like ltak-benum,
        vemng like vepo-vemng,
      end of px_tabi.
*
data: begin of pik_rep occurs 0,
        exidv like vekp-exidv,
        vemng_pik like vepo-vemng,
        vemng_rep like vepo-vemng,
      end of pik_rep.
*
** Variáveis auxiliares para o ALV
DATA: ok_code      LIKE sy-ucomm,
      grid_control TYPE REF TO cl_gui_alv_grid,
      container    TYPE REF TO cl_gui_custom_container,
      control      TYPE REF TO i_oi_container_control,
      variant      LIKE disvariant,
      repid        LIKE sy-repid,
      wa_layout    TYPE lvc_s_layo,
      wa_events   TYPE slis_alv_event,
      events      TYPE slis_t_event,
      layout       TYPE slis_layout_alv,
      it_fieldcat  TYPE slis_t_fieldcat_alv,
      sort         TYPE slis_t_sortinfo_alv,
      fieldcat     TYPE lvc_t_fcat,
      wa_fieldcat  TYPE lvc_s_fcat,
      itab_sort    TYPE lvc_t_sort,
      wa_sort      TYPE lvc_s_sort.

DATA: it_header     TYPE kkblo_t_listheader.
DATA:  v_linno           LIKE sy-linno.
DATA: header        TYPE kkblo_listheader.
data: zdiaseg type vekp-erdat,
      zhorafim type vekp-eruhr,
      zcontarep type vepo-vemng,
      zcontapik type vepo-vemng,
      ztotrep type vepo-vemng,
      ztotrep_g type vepo-vemng,
      ztotpik type vepo-vemng,
      zkpik type vepo-vemng,
      zmaispik type I,
      z_ltap_index type sy-index,
      zsscc_prod like vekp-exidv,
      zvbeln_ant like likp-vbeln,
      zexidv_ant like vekp-exidv,
      zerdat_sscc like vekp-erdat,
      zeruhr_sscc like vekp-eruhr,
      fl_sai like sy-subrc.
***************************************************************
