*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMSCRTOP.                        " Global Data
  INCLUDE LZWMSCRUXX.                        " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMSCRF00                              . " subprograms
  INCLUDE LZWMSCRI00                              . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMSCRF...                        " Subprograms
* INCLUDE LZWMSCRO...                        " PBO-Modules
* INCLUDE LZWMSCRI...                        " PAI-Modules
