*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMSCR3TOP.                       " Global Data
  INCLUDE LZWMSCR3UXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMSCR3F00                             . " subprograms
  INCLUDE LZWMSCR3I00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMSCR3F...                       " Subprograms
* INCLUDE LZWMSCR3O...                       " PBO-Modules
* INCLUDE LZWMSCR3I...                       " PAI-Modules
