*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZWMSCR10TOP.                      " Global Data
  INCLUDE LZWMSCR10UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZWMSCR10F00                            . " subprograms
  INCLUDE LZWMSCR10I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZWMSCR10F...                      " Subprograms
* INCLUDE LZWMSCR10O...                      " PBO-Modules
* INCLUDE LZWMSCR10I...                      " PAI-Modules
